#ifndef ENCODERPARAMETER_H
#define ENCODERPARAMETER_H

#define PULSES_PER_ROTATION         11
#define MOTOR_REDUCTION_RATIO       18.8f
#define WHEEL_DIAMETER_M            0.078f

#define SPEED_MESUREMENT_PERIOD_MS  100

#endif /* ENCODERPARAMETER_H */
